-- =============================================================================
-- Project: Kakadu / Equity ODS
-- File:   install_equity_schema.sql
-- Purpose: Full Database Infrastructure & Schema Initialization (V3 - Architecture Ready)
-- Target:  Oracle Autonomous Database (ADB)
-- Execution: Run as ADMIN user in OCI Database Actions / SQL Worksheet
-- -----------------------------------------------------------------------------
-- Architecture Layers Supported:
--   SYS -> System/Metadata (Logs, Config)
--   ODS -> Operational Data Store (Raw Landing)
--   REF -> Reference (Dictionaries, Mappings)
--   BDI -> Business Digital Image (Cleaned/Standardized - similar to DWD)
--   DMT -> Data Mart (Aggregated/Indicators)
-- =============================================================================
SET DEFINE OFF;

-- -----------------------------------------------------------------------------
-- 1. Create Custom Profile (Anti-Lockout, Anti-Expiration, Anti-Timeout)
-- -----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE PROFILE EQUITY_PROFILE LIMIT 
      PASSWORD_LIFE_TIME      UNLIMITED 
      FAILED_LOGIN_ATTEMPTS   UNLIMITED 
      PASSWORD_GRACE_TIME     UNLIMITED
      PASSWORD_REUSE_TIME     UNLIMITED
      PASSWORD_REUSE_MAX      UNLIMITED
      IDLE_TIME               UNLIMITED
      CONNECT_TIME            UNLIMITED';
EXCEPTION
  WHEN OTHERS THEN
    -- ORA-02379: profile already exists
    IF SQLCODE NOT IN (-2377, -2378, -2379) THEN RAISE; END IF; 
END;
/

-- -----------------------------------------------------------------------------
-- 2. Create EQUITY User Schema (Idempotent)
--    >>> EDIT "ChangeMe_Strong#2026" before executing <<<
-- -----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER EQUITY IDENTIFIED BY "ChangeMe2026!"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF; -- ORA-01920: User already exists
END;
/

-- -----------------------------------------------------------------------------
-- 3. Apply Profile, Tablespace & Storage Quota
-- -----------------------------------------------------------------------------
ALTER USER EQUITY PROFILE EQUITY_PROFILE;
ALTER USER EQUITY DEFAULT TABLESPACE DATA;
ALTER USER EQUITY QUOTA UNLIMITED ON DATA;

-- -----------------------------------------------------------------------------
-- 4. Grant ADB Application Roles & Explicit Privileges
-- -----------------------------------------------------------------------------
-- Full DBA for personal single-user schema management
GRANT DBA TO EQUITY;

-- Traditional roles
GRANT CONNECT TO EQUITY;
GRANT RESOURCE TO EQUITY;

-- DWROLE is the standard Autonomous Data Warehouse application role.
BEGIN
  EXECUTE IMMEDIATE 'GRANT DWROLE TO EQUITY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1919 THEN RAISE; END IF; 
END;
/

-- Core connection and object creation privileges
GRANT CREATE SESSION TO EQUITY;
GRANT CREATE TABLE TO EQUITY;
GRANT CREATE VIEW TO EQUITY;
GRANT CREATE PROCEDURE TO EQUITY;
GRANT CREATE SEQUENCE TO EQUITY;
GRANT CREATE TYPE TO EQUITY;
GRANT CREATE TRIGGER TO EQUITY;

-- Essential for asynchronous tasks, deduplication and indicator calculation jobs
GRANT CREATE JOB TO EQUITY;

-- -----------------------------------------------------------------------------
-- 5. Application Infrastructure: System Batch/Pipeline Logging
--    This table tracks the execution of all pipelines across different layers.
-- -----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE EQUITY.SYS_BATCH_LOG (
      LOG_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      BATCH_ID          VARCHAR2(50)   NOT NULL, -- Unique ID for the entire run (e.g., "20260124_01")
      LAYER             VARCHAR2(10)   NOT NULL, -- Layer: SYS, ODS, REF, BDI, DMT
      PIPELINE_NAME     VARCHAR2(100)  NOT NULL, -- e.g., "YAHOO_LOAD", "SENSITIVE_CALC"
      STEP_NAME         VARCHAR2(100),           -- e.g., "FETCH", "DEDUPE", "AGGREGATE"
      START_TIME        TIMESTAMP      DEFAULT SYSTIMESTAMP,
      END_TIME          TIMESTAMP,
      STATUS            VARCHAR2(20),           -- "RUNNING", "SUCCESS", "FAILED", "WARNING"
      RECORDS_PROCESSED NUMBER,                 -- Rows affected
      ERROR_MESSAGE     VARCHAR2(4000),         -- Error stack
      SOURCE_SYSTEM     VARCHAR2(30),           -- "YAHOO", "AFR", "ASX", "INTERNAL"
      
      -- Enforce Data Warehouse Layering Standards
      CONSTRAINT SYS_BATCH_LOG_LAYER_CK CHECK (LAYER IN ('SYS', 'ODS', 'REF', 'BDI', 'DMT'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; -- ORA-00955: name already used
END;
/

-- Create index for fast lookup of a specific batch's progress
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX EQUITY.IDX_SYS_BATCH_LOG_BID ON EQUITY.SYS_BATCH_LOG(BATCH_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; 
END;
/

-- -----------------------------------------------------------------------------
-- 6. Verification Check
-- -----------------------------------------------------------------------------
PROMPT =====================================================================
PROMPT EQUITY Schema Initialization Complete.
PROMPT ---------------------------------------------------------------------
PROMPT [OK] Profile: EQUITY_PROFILE assigned.
PROMPT [OK] Quota:   UNLIMITED ON DATA.
PROMPT [OK] Roles:   DWROLE, CREATE JOB granted.
PROMPT [OK] Infra:   EQUITY.SYS_BATCH_LOG created (Supports SYS, ODS, REF, BDI, DMT).
PROMPT =====================================================================

COMMIT;